"""Add item_id to claims

Revision ID: d333cfa7ffb1
Revises: 
Create Date: 2024-09-20 07:41:49.764533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd333cfa7ffb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'claims', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'item_id')
    # ### end Alembic commands ###
